name: Run bot

on:
  push:
    branches:
      - main

jobs:
  Run_bot:
    env:
      TOKEN: ${{ secrets.TOKEN }}
    runs-on: macos-latest
    steps:
      - uses: actions/setup-python@v5.2.0
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m pip install -U discord.py --break-system-packages
          python3 -m pip install requests --break-system-packages
      - name: Run bot
        run: |
          python3 ./zigister.py
